### Verificar que el servidor está corriendo
GET http://localhost:4501/
###

### Recuperar todos los empleados
GET http://localhost:4501/api/empleados
###

### Crear un empleado con POST
POST http://localhost:4501/api/empleados
Content-Type: application/json

{
  "nombre": "Mariana Pulmón",
  "rol": "médico",
  "area": "Atención Médica"
}
###

### Recuperar un empleado por ID
GET http://localhost:4501/api/empleados/6bd6c6c5-f0e8-4e3f-9e40-c0b3b98dd418
###

### Actualizar un dato de un empleado con PUT
PUT http://localhost:4501/api/empleados/6bd6c6c5-f0e8-4e3f-9e40-c0b3b98dd418
Content-Type: application/json

{
  "nombre": "Carlos A. Corazón"
}
###

### Borrar un empleado con DELETE
DELETE http://localhost:4501/api/empleados/0d3d0f27-3713-4010-8dd9-649f1db40b09
###