POST http://localhost:4501/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

### Listar todos los turnos
GET http://localhost:4501/api/turnos
Content-Type: application/json

###

### Obtener un turno por ID
GET http://localhost:4501/api/turnos/2b0ec632-391d-484d-ad31-7f8fb1201f77
Content-Type: application/json

###

### Crear un nuevo turno
POST http://localhost:4501/api/turnos
Content-Type: application/json

{
  "pacienteId": 3,
  "empleadoId": 103,
  "fechaInicio": "2025-09-20T10:00:00",
  "fechaFin": "2025-09-20T10:30:00",
  "prioridad": "baja",
  "estado": "pendiente",
  "observaciones": "Consultorio 1"
}

###

### Actualizar un turno existente
PUT http://localhost:4501/api/turnos/c355d75a-332d-459d-9621-8dab6a38d3c8
Content-Type: application/json

{   "pacienteId": 1,
    "empleadoId": 101,
  "fechaInicio": "2025-09-20T11:00:00",
  "fechaFin": "2025-09-20T11:30:00",
  "prioridad": "alta",
  "estado": "en proceso"
}

###

### Eliminar un turno por ID
DELETE http://localhost:4501/api/turnos/c355d75a-332d-459d-9621-8dab6a38d3c8
Content-Type: application/json
